In [2]:
import numpy as np

In [3]:
w = np.array(range(100))

In [4]:
w

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
e = np.zeros(9)

In [6]:
e

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
f = np.zeros(10).reshape(2,5)
f

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
d = np.ones(10)
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
d = np.ones(10).reshape(2,5)
d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
f = np.cumsum(d)
f

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
f1 = np.cumprod(f)
f1

array([1.0000e+00, 2.0000e+00, 6.0000e+00, 2.4000e+01, 1.2000e+02,
       7.2000e+02, 5.0400e+03, 4.0320e+04, 3.6288e+05, 3.6288e+06])

In [12]:
f = np.cumproduct(f)
f

array([1.0000e+00, 2.0000e+00, 6.0000e+00, 2.4000e+01, 1.2000e+02,
       7.2000e+02, 5.0400e+03, 4.0320e+04, 3.6288e+05, 3.6288e+06])

In [13]:
f = np.random.randn(10)
f

array([-1.02432157, -1.40532377, -0.10196776,  1.21103799,  1.0838381 ,
        0.60270397, -0.19260449, -1.16294197,  1.49779901, -0.50064657])

In [14]:
f = np.random.randint(10)
f

7

In [15]:
f = np.random.bytes(100)
f

b'\x19\xba5\xe0!\xb4\\4\xd5\x9c\\\xee;\x1d\x08\xf8g\xce\x02f}\xe1\xd8\x03\xfb=\x03JT\x85\xf9Zq\x04\x04`j,\nGs/\xbf"\xbe\x93\x85\xa1\xd2\xde\xe4\xf8\x00\xeb\xd9>\x15)\x7f\x89\xa2A\x0eq\n\xcd\x1a\x1ax\xed5\x1b$8M\xfbz\xf8\x1fm\xc3\xff\xfa\rZ\xca\x18\xb3\xb0\xad(\xabc\xce\x83\xeb\'\x85\xda#'

In [16]:
d = np.array(range(10))
f = d[d>5]
np.sum(f)

30

In [17]:
a = np.array(range(5))
x = np.amax(a)
x

4

In [18]:
a = np.array(range(5))
x = np.amin(a)
x

0

In [19]:
a = np.array([True,False,True])
np.alltrue(a)


False

In [20]:
np.any(a)

True

In [21]:
a = np.array([3,-4,34.3,2])
np.absolute(a)

array([ 3. ,  4. , 34.3,  2. ])

In [22]:
a = np.arange(10).reshape(2,5)
np.double(a)


array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [23]:
a = np.arange(10).reshape(2,5)
np.trace(a)


6

In [24]:
a = np.arange(10).reshape(2,5)
np.angle(a)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
a = np.arange(10).reshape(2,5)
np.average(a)


4.5

In [26]:
a = np.array([10,9,8,7,6,5])
np.sort(a)


array([ 5,  6,  7,  8,  9, 10])

In [27]:
a = np.arange(10).reshape(2,5)
np.argmax(a)


9

In [28]:
a = np.arange(10).reshape(2,5)
np.argmin(a)


0

In [29]:
a = np.arange(10).reshape(2,5)
np.where(a)


(array([0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int32),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int32))

In [30]:
a = np.arange(10).reshape(2,5)
np.cos(a)


array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026]])

In [31]:
a = np.arange(10).reshape(2,5)
np.sin(a)


array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [32]:
a = np.arange(10).reshape(2,5)
np.tan(a)


array([[ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128],
       [-3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566]])

In [33]:
np.degrees(a)

array([[  0.        ,  57.29577951, 114.59155903, 171.88733854,
        229.18311805],
       [286.47889757, 343.77467708, 401.07045659, 458.3662361 ,
        515.66201562]])

In [34]:
np.ceil(a)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [35]:
np.floor(a)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [39]:
np.ndim(a)


2

In [40]:
np.shape(a)

(2, 5)

In [45]:
a = np.empty(10).reshape(2,5)
a

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [50]:
a = np.full(10,3).reshape(5,2)
a

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [51]:
np.transpose(a)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [52]:
np.sqrt(a)

array([[1.73205081, 1.73205081],
       [1.73205081, 1.73205081],
       [1.73205081, 1.73205081],
       [1.73205081, 1.73205081],
       [1.73205081, 1.73205081]])

In [53]:
np.exp(a)

array([[20.08553692, 20.08553692],
       [20.08553692, 20.08553692],
       [20.08553692, 20.08553692],
       [20.08553692, 20.08553692],
       [20.08553692, 20.08553692]])

In [57]:
a = np.arange(10).reshape(5,2)
reminder,whole_part = np.modf(a)

In [58]:
reminder

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [59]:
whole_part


array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [60]:
np.square(a)

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]], dtype=int32)

In [61]:
np.rint(a)

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [63]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [62]:
c = np.where(a>5)
c

(array([3, 3, 4, 4], dtype=int32), array([0, 1, 0, 1], dtype=int32))

In [64]:
np.argmin(a)

0

In [65]:
np.argmax(a)

9

In [66]:
a = np.array([1,1,3,3,4,4,6,5,3,3])
np.unique(a)

array([1, 3, 4, 5, 6])

In [67]:
a = np.array([1,3,5,7,9])
b = np.array([2,4,6,8,10])
np.union1d(a,b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
a = np.array([1,2,3,5,7,9])
b = np.array([2,4,6,8,7,10])
np.intersect1d(a,b)

array([2, 7])

In [69]:
np.in1d(a,b)

array([False,  True, False, False,  True, False])

In [70]:
np.setdiff1d(a,b)

array([1, 3, 5, 9])

In [71]:
np.setxor1d(a,b)

array([ 1,  3,  4,  5,  6,  8,  9, 10])

In [72]:
a.dot(b)

207

In [73]:
np.dot(a,b)

207

In [74]:
np.diag(a)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 9]])

In [76]:
np.diagflat(a)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 9]])

In [79]:
np.random.normal(size=(4,4))

array([[ 0.1600461 ,  1.69133142,  0.27703151, -2.17475984],
       [ 0.1699334 ,  0.60128432, -1.14213053, -0.82328632],
       [-1.0171806 ,  0.0177914 , -0.84568946, -0.32267796],
       [-0.3149832 ,  0.74356818,  0.98430189,  0.713469  ]])

In [84]:
np.random.RandomState(124)

RandomState(MT19937) at 0x471B848

In [87]:
a = np.random.seed(342)
a